sudo: required
services:
  - docker

before_install:
  - docker build -t joshensley/docker-react -f Dockerfile.dev .

script:
  - docker run joshensley/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: # view video "102 Travis Config for Deployment"
  app: # view video "102 Travis Config for Deployment"
  env: # view video "102 Travis Config for Deployment"
  bucket_name: # view video "102 Travis Config for Deployment"
  bucket_path: # view video "102 Travis Config for Deployment"
  on:
    branch: master
  access_key_id: # view video "104 Automated Deployments"
  secret_access_key:
    secure: # view video "104 Automated Deployments"
